"""users table

Revision ID: 947bd420a76d
Revises: 
Create Date: 2018-06-04 01:07:54.691111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947bd420a76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numu_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_numu_user_email'), 'numu_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_numu_user_email'), table_name='numu_user')
    op.drop_table('numu_user')
    # ### end Alembic commands ###
