########################################
# For REST Client VSCode (Huachao Mao) #
#--------------------------------------#
# Local Server                         #
########################################

### Register Account
curl "http://localhost/v3/user" -X POST -H "Content-Type: application/json" -d '{"email":"test@test.com","password":"TestingP@ssword"}'

### Get User Info
curl "http://localhost/v3/user" -u "test@test.com:TestingP@ssword"

### Get Token
curl "http://localhost/v3/user/token" -u "test@test.com:TestingP@ssword" 

### Try Token
curl "http://localhost/v3/user" -u "eyJhbGciOiJIUzI1NiIsImlhdCI6MTUyOTc4NzQxNSwiZXhwIjoxNTI5Nzg4MDE1fQ.eyJpZCI6Njd9.nKxW7Yb-udiXjm056Uega5KmW06_kj2t6c-oWplcjSw:"

### Import LastFM Artists
curl "http://localhost/v3/user/import/lastfm" -u "test@test.com:TestingP@ssword" -X POST  -H "Content-Type: application/json" -d '{"username":"amiantos","period":"overall"}'







########################################
# Remote Server                        #
########################################

### Register Account
curl "https://api.numutracker.com/v3/user" -X POST -H "Content-Type: application/json" -d '{"email":"test@test.com","password":"TestingP@ssword"}'

### Get User Info
curl "https://api.numutracker.com/v3/user" -u "test@test.com:TestingP@ssword"

### Get Token
curl "https://api.numutracker.com/v3/user/token" -u "test@test.com:TestingP@ssword"

### Try Token
curl "https://api.numutracker.com/v3/user" -u "eyJhbGciOiJIUzI1NiIsImlhdCI6MTUyOTc4NzIwOCwiZXhwIjoxNTI5Nzg3ODA4fQ.eyJpZCI6MX0.ZtonBJhhpEZe8T4s9v6w6kHVMKy9_aA9eJpI4gfAi4A:"
