"""add index for artist name

Revision ID: 1133b0fe3625
Revises: b9acd1a349f9
Create Date: 2019-01-08 04:01:10.053528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1133b0fe3625'
down_revision = 'b9acd1a349f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('artist_name', 'artist', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('artist_name', table_name='artist')
    # ### end Alembic commands ###
