"""update user release table

Revision ID: 1f334e892ddb
Revises: fd69c4cb847d
Create Date: 2018-12-22 01:38:49.530212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f334e892ddb'
down_revision = 'fd69c4cb847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_release', sa.Column('date_checked', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_release', 'art')
    op.drop_column('user_artist', 'art')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_artist', sa.Column('art', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_release', sa.Column('art', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user_release', 'date_checked')
    # ### end Alembic commands ###
