"""add uuid columns for user_artist and user_release tables

Revision ID: 322f5709da9f
Revises: 1133b0fe3625
Create Date: 2019-02-03 04:07:45.836684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322f5709da9f'
down_revision = '1133b0fe3625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_artist', sa.Column('uuid', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_artist_uuid'), 'user_artist', ['uuid'], unique=True)
    op.add_column('user_release', sa.Column('user_artist_uuid', sa.String(), nullable=False))
    op.add_column('user_release', sa.Column('uuid', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_release_user_artist_uuid'), 'user_release', ['user_artist_uuid'], unique=False)
    op.create_index(op.f('ix_user_release_uuid'), 'user_release', ['uuid'], unique=True)
    op.create_foreign_key(None, 'user_release', 'user_artist', ['user_artist_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_release', type_='foreignkey')
    op.drop_index(op.f('ix_user_release_uuid'), table_name='user_release')
    op.drop_index(op.f('ix_user_release_user_artist_uuid'), table_name='user_release')
    op.drop_column('user_release', 'uuid')
    op.drop_column('user_release', 'user_artist_uuid')
    op.drop_index(op.f('ix_user_artist_uuid'), table_name='user_artist')
    op.drop_column('user_artist', 'uuid')
    # ### end Alembic commands ###
