"""add date_v2_import column to user model

Revision ID: 41082bcd0b58
Revises: f2dce16bc8d1
Create Date: 2019-02-12 00:15:55.261608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41082bcd0b58'
down_revision = 'f2dce16bc8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_v2_import', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_v2_import')
    # ### end Alembic commands ###
