"""add back user_release.art table

Revision ID: 4ff954d96d2a
Revises: 1f334e892ddb
Create Date: 2018-12-22 01:39:16.392435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff954d96d2a'
down_revision = '1f334e892ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_release', sa.Column('art', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_artist', sa.Column('art', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_release', 'art')
    op.drop_column('user_artist', 'art')
    # ### end Alembic commands ###
