"""remove unnecessary columns, change link column format

Revision ID: 6c4a502736e7
Revises: 41082bcd0b58
Create Date: 2019-02-14 20:55:16.622874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c4a502736e7'
down_revision = '41082bcd0b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_artist_release_user_artist_uuid', table_name='user_artist_release')
    op.drop_index('ix_user_artist_release_user_release_uuid', table_name='user_artist_release')
    op.drop_table('user_artist_release')
    op.add_column('artist', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_index('artist_sort_name', 'artist', ['sort_name'], unique=False)
    op.drop_column('artist', 'spotify_link')
    op.drop_column('artist', 'apple_music_link')
    op.add_column('release', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.drop_column('release', 'spotify_link')
    op.drop_column('release', 'apple_music_link')
    op.alter_column('user_artist', 'date_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('user_artist', 'sort_name')
    op.drop_column('user_artist', 'name')
    op.drop_index('ix_user_release_date_release', table_name='user_release')
    op.drop_index('ix_user_release_type', table_name='user_release')
    op.drop_index('user_releases', table_name='user_release')
    op.drop_index('user_releases_listened', table_name='user_release')
    op.drop_column('user_release', 'spotify_link')
    op.drop_column('user_release', 'art')
    op.drop_column('user_release', 'apple_music_link')
    op.drop_column('user_release', 'title')
    op.drop_column('user_release', 'artist_names')
    op.drop_column('user_release', 'type')
    op.drop_column('user_release', 'date_release')
    op.drop_column('user_release', 'date_checked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_release', sa.Column('date_checked', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_release', sa.Column('date_release', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('user_release', sa.Column('type', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('user_release', sa.Column('artist_names', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_release', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_release', sa.Column('apple_music_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_release', sa.Column('art', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_release', sa.Column('spotify_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('user_releases_listened', 'user_release', ['user_id', 'type', 'listened', 'date_release'], unique=False)
    op.create_index('user_releases', 'user_release', ['user_id', 'type', 'date_release'], unique=False)
    op.create_index('ix_user_release_type', 'user_release', ['type'], unique=False)
    op.create_index('ix_user_release_date_release', 'user_release', ['date_release'], unique=False)
    op.add_column('user_artist', sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('user_artist', sa.Column('sort_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.alter_column('user_artist', 'date_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('release', sa.Column('apple_music_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('release', sa.Column('spotify_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('release', 'links')
    op.add_column('artist', sa.Column('apple_music_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('spotify_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('artist_sort_name', table_name='artist')
    op.drop_column('artist', 'links')
    op.create_table('user_artist_release',
    sa.Column('user_artist_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_release_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_artist_uuid'], ['user_artist.uuid'], name='user_artist_release_user_artist_uuid_fkey', onupdate='CASCADE', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_release_uuid'], ['user_release.uuid'], name='user_artist_release_user_release_uuid_fkey', onupdate='CASCADE', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('user_artist_uuid', 'user_release_uuid', name='user_artist_release_pkey')
    )
    op.create_index('ix_user_artist_release_user_release_uuid', 'user_artist_release', ['user_release_uuid'], unique=False)
    op.create_index('ix_user_artist_release_user_artist_uuid', 'user_artist_release', ['user_artist_uuid'], unique=False)
    # ### end Alembic commands ###
