"""added more indexes

Revision ID: 7bad0b3188e3
Revises: 339c0e295c93
Create Date: 2020-01-23 21:48:03.156222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bad0b3188e3'
down_revision = '339c0e295c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artist_date_updated'), 'artist', ['date_updated'], unique=False)
    op.create_index(op.f('ix_release_date_updated'), 'release', ['date_updated'], unique=False)
    op.create_index(op.f('ix_user_artist_date_updated'), 'user_artist', ['date_updated'], unique=False)
    op.create_index(op.f('ix_user_release_date_updated'), 'user_release', ['date_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_release_date_updated'), table_name='user_release')
    op.drop_index(op.f('ix_user_artist_date_updated'), table_name='user_artist')
    op.drop_index(op.f('ix_release_date_updated'), table_name='release')
    op.drop_index(op.f('ix_artist_date_updated'), table_name='artist')
    # ### end Alembic commands ###
