"""add api_token table

Revision ID: b44e10c1f032
Revises: baee0a6588d1
Create Date: 2019-02-15 22:01:31.260211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44e10c1f032'
down_revision = 'baee0a6588d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_token')
    # ### end Alembic commands ###
