"""remove some unnecessary denormalized fields

Revision ID: b9acd1a349f9
Revises: f115cda1ba1c
Create Date: 2018-12-26 20:45:15.173720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9acd1a349f9'
down_revision = 'f115cda1ba1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_artist', 'apple_music_link')
    op.drop_column('user_artist', 'disambiguation')
    op.drop_column('user_artist', 'art')
    op.drop_column('user_artist', 'date_checked')
    op.drop_column('user_artist', 'spotify_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_artist', sa.Column('spotify_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_artist', sa.Column('date_checked', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_artist', sa.Column('art', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_artist', sa.Column('disambiguation', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('user_artist', sa.Column('apple_music_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
