"""add date_checked column to user_artist

Revision ID: bf9ea959d63b
Revises: 4ff954d96d2a
Create Date: 2018-12-22 02:05:31.200935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9ea959d63b'
down_revision = '4ff954d96d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_artist', sa.Column('apple_music_link', sa.String(), nullable=True))
    op.add_column('user_artist', sa.Column('date_checked', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_artist', sa.Column('spotify_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_artist', 'spotify_link')
    op.drop_column('user_artist', 'date_checked')
    op.drop_column('user_artist', 'apple_music_link')
    # ### end Alembic commands ###
