"""add follow columns to user_release table

Revision ID: f2dce16bc8d1
Revises: f7fa96222aa4
Create Date: 2019-02-09 16:00:40.026781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f2dce16bc8d1"
down_revision = "f7fa96222aa4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_release', sa.Column('date_followed', sa.DateTime(timezone=True), nullable=False))
    op.alter_column(
        "user_release", "date_added", nullable=False, new_column_name="date_followed"
    )
    op.add_column(
        "user_release", sa.Column("follow_method", sa.String(), nullable=True)
    )
    op.add_column("user_release", sa.Column("following", sa.Boolean(), nullable=True))
    op.execute(
        """
        UPDATE user_release
        SET following = 'true',
        follow_method = 'AUTOMATIC'
    """
    )
    op.create_index(
        op.f("ix_user_release_following"), "user_release", ["following"], unique=False
    )
    # op.drop_column("user_release", "date_added")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_release', sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column(
        "user_release", "date_followed", nullable=False, new_column_name="date_added"
    )
    op.drop_index(op.f("ix_user_release_following"), table_name="user_release")
    op.drop_column("user_release", "following")
    op.drop_column("user_release", "follow_method")
    # op.drop_column("user_release", "date_followed")
    # ### end Alembic commands ###
