"""add user_artist_release table

Revision ID: f40c26a39c78
Revises: 57dd1d5b6c9f
Create Date: 2019-02-03 21:48:48.960287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40c26a39c78'
down_revision = '57dd1d5b6c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_artist_release',
    sa.Column('user_artist_uuid', sa.String(), nullable=False),
    sa.Column('user_release_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_artist_uuid'], ['user_artist.uuid'], onupdate='CASCADE', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_release_uuid'], ['user_release.uuid'], onupdate='CASCADE', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('user_artist_uuid', 'user_release_uuid')
    )
    op.create_index(op.f('ix_user_artist_release_user_artist_uuid'), 'user_artist_release', ['user_artist_uuid'], unique=False)
    op.create_index(op.f('ix_user_artist_release_user_release_uuid'), 'user_artist_release', ['user_release_uuid'], unique=False)
    op.drop_index('ix_user_release_user_artist_uuid', table_name='user_release')
    op.drop_constraint('user_release_user_artist_uuid_fkey', 'user_release', type_='foreignkey')
    op.drop_column('user_release', 'user_artist_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_release', sa.Column('user_artist_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_release_user_artist_uuid_fkey', 'user_release', 'user_artist', ['user_artist_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_user_release_user_artist_uuid', 'user_release', ['user_artist_uuid'], unique=False)
    op.drop_index(op.f('ix_user_artist_release_user_release_uuid'), table_name='user_artist_release')
    op.drop_index(op.f('ix_user_artist_release_user_artist_uuid'), table_name='user_artist_release')
    op.drop_table('user_artist_release')
    # ### end Alembic commands ###
