"""remove art columns

Revision ID: f7b5f2f4cfa5
Revises: e11a57c718d0
Create Date: 2018-12-21 00:42:41.418872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b5f2f4cfa5'
down_revision = 'e11a57c718d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'art')
    op.drop_column('release', 'art')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('art', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('art', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
