"""add back proper art columns

Revision ID: fd69c4cb847d
Revises: f7b5f2f4cfa5
Create Date: 2018-12-21 00:45:05.294658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd69c4cb847d'
down_revision = 'f7b5f2f4cfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('art', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('release', sa.Column('art', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'art')
    op.drop_column('artist', 'art')
    # ### end Alembic commands ###
